### ISSUE TITLE
Update CFFs once Zenodo DOIs have been minted for archived versions

### ISSUE THREAD

**Issue by jbstatgen** [tdwg/ltc#70]
From citation.CFF:
```
identifiers:
  - type: "doi"
    value: "10.xxxxxx"
    description: "DOI for this repository archived in Zenodo"
repository-code: "https://github.com/tdwg/ltc"
url: "https://github.com/tdwg/ltc/wiki"
```
citation_release.CFF:
```
identifiers:
  - type: "doi"
    value: "10.xxxxxx"
    description: "DOI for this repository archived in Zenodo"
repository-code: "https://github.com/tdwg/ltc/"
url: "https://tdwg.github.io/ltc/"
```
The CFF standard allows the association of identifiers with the publication or published resource, e.g. a DOI. 
We thought it sensible, once LtC is ratified to archive the release version and a current repository snapshot on Zenodo. This apparently will generate a DOI for each of them.
Once this is done, the CFFs should be updated with the DOIs (currently a placeholder is present).

Alternatively, the identifier keyword should be removed from the CFFs.
